### ISSUE TITLE
UX Update - Product Quote Unit Field

### ISSUE THREAD

**Issue by jamacon36** [temperandforge/RDE-reade#10]
## Overview
The unit field in the Product Quote request form needs to be updated with better placeholder implementation and to be required.

## Figma Link
- https://www.figma.com/design/NYa8HLeC5OKzajbUK808rE/T%26F-%2F%2F-Reade?node-id=6910-14594&m=dev

## Dev Tasks
- [x] Update the field placeholder attribute to be "Unit"
- [x] Make the field required
- [x] Update placeholder styling to be consistent with the direction in the dev annotation

**Comment by scott-temper-forge** [comment]
Made units a placeholder with placeholder styling
made it required
