### ISSUE TITLE
Move Dev To Production

### ISSUE THREAD

**Issue by scott-temper-forge** [temperandforge/RDE-reade#15]
Moving dev code to production

- [x] Sync production to staging
- [x] Merge dev code into staging
- [x] Update links and text to match figma
- [x] Do a final pass to verify all links go to their correct landing page and all text matches figma
- [x] Copy staging environment to production
- [x] Test CRM on production with product rfq and custom product submissions
- [x] Let Jillian know two submissions came in

**Comment by scott-temper-forge** [comment]
@jamacon36 Should we test product submission on staging AND on production?  May seem like overkill, but that is the whole point of their website and thus super critical.

**Comment by jamacon36** [comment]
@scott-temper-forge we should be fine to test on prod once the deploy is complete.
